"""Pydantic v2 models for the OpenAI-compatible wire format."""

from app.schemas.openai import (
    ChatCompletionChunk,
    ChatCompletionRequest,
    ChatCompletionResponse,
    ChatMessage,
    Choice,
    ChunkChoice,
    ChunkDelta,
    EmbeddingItem,
    EmbeddingsRequest,
    EmbeddingsResponse,
    EmbeddingsUsage,
    FunctionCall,
    FunctionDef,
    HealthResponse,
    Model,
    ModelList,
    ResponseFormat,
    ResponseMessage,
    Tool,
    ToolCall,
    Usage,
)

__all__ = [
    "ChatCompletionChunk",
    "ChatCompletionRequest",
    "ChatCompletionResponse",
    "ChatMessage",
    "Choice",
    "ChunkChoice",
    "ChunkDelta",
    "EmbeddingItem",
    "EmbeddingsRequest",
    "EmbeddingsResponse",
    "EmbeddingsUsage",
    "FunctionCall",
    "FunctionDef",
    "HealthResponse",
    "Model",
    "ModelList",
    "ResponseFormat",
    "ResponseMessage",
    "Tool",
    "ToolCall",
    "Usage",
]
